name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List . files
      run: |
        pwd
        ls -la

    - name: List files /__w
      run: |
        ls -la /__w

    - name: Install alpine-sdk and other needed packages
      run: |
        apk update
        apk add alpine-sdk alpine-conf syslinux xorriso squashfs-tools grub grub-efi doas mtools dosfstools grub-efi

    - name: Install expect
      run: |
        apk update
        apk add expect

    - name: Create signing keys
      run: |
        chmod +x abuild-keygen.exp
        ./abuild-keygen.exp

    - name: Copy public key into /etc/apk/keys
      run: |
        cp ~/.abuild/*.pub /etc/apk/keys/

    - name: List /etc/apk/keys
      run: |
        ls -la /etc/apk/keys/

    - name: Install git
      run: |
        apk update
        apk add git

    - name: Clone aports repo
      run: |
        git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git

    - name: Create new, big tmp directory
      run: |
        mkdir -pv ~/tmp
        export TMPDIR=~/tmp
        echo "export TMPDIR=~/tmp" >> ~/.profile

    - name: Conf PROFILENAME
      run: |
        export PROFILENAME=esxi-passwordreset
        echo "export PROFILENAME=esxi-passwordreset" >> ~/.profile

    - name: Build
      run: |
        sh /home/build/aports/scripts/mkimage.sh --tag edge --outdir ~/iso --arch x86_64 --repository https://dl-cdn.alpinelinux.org/alpine/edge/main --extra-repository https://dl-cdn.alpinelinux.org/alpine/edge/community --profile esxi-passwordreset
