name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:

    - name: Update packages
      run: |
        pacman -Sy --noconfirm

    - name: Install git
      run: |
        pacman -S --noconfirm git

    - name: Install archiso
      run: |
        pacman -S --noconfirm archiso

    - name: Clone esxi-password repo
      run: |
        git clone https://github.com/filip2cz/esxi-passwordreset.git .

    - name: Prepare a custom profile
      run: |
        cp -r /usr/share/archiso/configs/releng/ archlive

    - name: Copy custom files into profile
      run: |
        cp ./custom-archlive/packages.x86_64 ./archlive/packages.x86_64
        cp ./custom-archlive/profiledef.sh ./archlive/profiledef.sh
        cp ./custom-archlive/airootfs/etc/os-release ./archlive/airootfs/etc/os-release
        mkdir ./archlive/airootfs/etc/esxi-passwordreset
        cp ./custom-archlive/airootfs/etc/esxi-passwordreset/script.bash ./archlive/airootfs/etc/esxi-passwordreset/script.bash

    - name: Create output dir
      run: |
        mkdir iso

    - name: Create working directory
      run: |
        mkdir working

    - name: List all files
      run: |
        ls -la

    - name: Give me all permissions please
      run: |
        chmod -R 777 ./archlive
        chmod -R 777 ./working

    - name: Build the ISO
      run: |
        mkarchiso -v -w ./working -o ./iso ./archlive/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: iso
        path: ./iso/esxi-passwordreset.iso

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: iso
          path: ./

      - name: Create new release and upload iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --draft tmp esxi-passwordreset.iso