name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install alpine-sdk and other needed packages
      run: |
        apk update
        apk add alpine-sdk alpine-conf syslinux xorriso squashfs-tools grub grub-efi doas

    - name: Clone aports repo
      run: |
        git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git

    - name: Run mkimage
      run: |
        cd aports/scripts
        ./mkimage.sh  \
        --profile custom \
        --arch x86_64 \
        --repository http://uk.alpinelinux.org/alpine/latest-stable/main \
        --outdir /root/iso/ \
        --tag BADGE