name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install alpine-sdk and other needed packages
      run: |
        apk update
        apk add alpine-sdk alpine-conf syslinux xorriso squashfs-tools grub grub-efi doas mtools dosfstools grub-efi

    - name: Add user into abuild group
      run: |
        usermod -a -G abuild root

    - name: Clone aports repo
      run: |
        git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git